# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'confirm_send.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_confirmSend(object):
    def setupUi(self, confirmSend):
        confirmSend.setObjectName("confirmSend")
        confirmSend.resize(237, 115)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(confirmSend.sizePolicy().hasHeightForWidth())
        confirmSend.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(confirmSend)
        self.verticalLayout.setContentsMargins(22, 22, 22, 22)
        self.verticalLayout.setSpacing(22)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dialogLabel = QtWidgets.QLabel(confirmSend)
        self.dialogLabel.setObjectName("dialogLabel")
        self.verticalLayout.addWidget(self.dialogLabel)
        self.buttonBox = QtWidgets.QDialogButtonBox(confirmSend)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(confirmSend)
        self.buttonBox.accepted.connect(confirmSend.accept)
        self.buttonBox.rejected.connect(confirmSend.reject)
        QtCore.QMetaObject.connectSlotsByName(confirmSend)

    def retranslateUi(self, confirmSend):
        _translate = QtCore.QCoreApplication.translate
        confirmSend.setWindowTitle(_translate("confirmSend", "Dialog"))
        self.dialogLabel.setText(_translate("confirmSend", "TextLabel"))
