# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'send_status.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sendStatus(object):
    def setupUi(self, sendStatus):
        sendStatus.setObjectName("sendStatus")
        sendStatus.resize(250, 110)
        sendStatus.setMinimumSize(QtCore.QSize(250, 110))
        self.verticalLayout = QtWidgets.QVBoxLayout(sendStatus)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(sendStatus)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(sendStatus)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.buttonBox = QtWidgets.QDialogButtonBox(sendStatus)
        self.buttonBox.setEnabled(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(sendStatus)
        self.buttonBox.clicked['QAbstractButton*'].connect(sendStatus.close)
        QtCore.QMetaObject.connectSlotsByName(sendStatus)

    def retranslateUi(self, sendStatus):
        _translate = QtCore.QCoreApplication.translate
        sendStatus.setWindowTitle(_translate("sendStatus", "Dialog"))
        self.label.setText(_translate("sendStatus", "TextLabel"))
